# The URL the site will be built for
base_url = "https://tavi.fyi"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# taxonomies = [{ name = "tags", feed = false }]

[markdown]
highlight_code = true
render_emoji = true
smart_punctuation = true
extra_syntaxes_and_themes = ["syntaxes"]
# highlight_theme = "1337"
# highlight_theme = "boron"
# highlight_theme = "charcoal"
# highlight_theme = "dracula"
# highlight_theme = "kronuz"
# highlight_theme = "material-dark"
highlight_theme = "monokai"
# highlight_themes_css = [
#     { theme = "monokai", filename = "syntax-theme-monokai.css" },
# ]
# highlight_theme = "nyx-bold"

[search]
index_format = "elasticlunr_json"
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = true
# Whether to include the path of the page/section in the index
include_path = true
# Whether to include the rendered content of the page/section in the index
include_content = true

[extra]
# Put all your custom variables here
